/**
 * Image provenance for catalog entities.
 *
 * Every entity image is an illustration made for this project (AI-generated
 * or a procedural "archival plate"), not historical artwork. The data lives
 * in `src/data/image-provenance.json`, generated by
 * `scripts/build_image_provenance.py`. UI can use `getImageProvenance` to
 * label images, e.g. "Illustrative image (AI-generated)".
 */
import provenanceData from "@/data/image-provenance.json";
import type { ImageEntityType, ImageProvenanceKind } from "@/lib/schemas";

export type { ImageEntityType, ImageProvenanceKind } from "@/lib/schemas";

export interface ImageProvenance {
  /** Key in the generators table, e.g. "ai-illustration". */
  generator: string;
  kind: ImageProvenanceKind;
  /** Short human label, e.g. "AI-generated illustration". */
  label: string;
  description: string;
  license?: string;
  source?: string;
  /** Repository scripts that produced images of this kind. */
  scripts?: string[];
}

interface ProvenanceFile {
  generators: Record<string, Omit<ImageProvenance, "generator">>;
  entities: Partial<Record<ImageEntityType, Record<string, string>>>;
}

const provenance = provenanceData as unknown as ProvenanceFile;

/**
 * Provenance of the image for `id` in the `entityType` catalog, or
 * undefined when the entity has no local image on record.
 */
export function getImageProvenance(
  entityType: ImageEntityType,
  id: string,
): ImageProvenance | undefined {
  const generator = provenance.entities[entityType]?.[id];
  if (!generator) return undefined;
  const details = provenance.generators[generator];
  if (!details) return undefined;
  return { generator, ...details };
}

/** True for images made for the project rather than sourced artwork. */
export function isIllustrativeImage(
  image: Pick<ImageProvenance, "kind"> | undefined,
): boolean {
  return (
    image?.kind === "illustration-ai" ||
    image?.kind === "illustration-procedural"
  );
}

/** How many catalog images were made each way, e.g. for the About page. */
export function countImagesByKind(): Record<ImageProvenanceKind, number> {
  const counts: Record<ImageProvenanceKind, number> = {
    "illustration-ai": 0,
    "illustration-procedural": 0,
    "public-domain": 0,
    licensed: 0,
    unverified: 0,
  };
  for (const byId of Object.values(provenance.entities)) {
    for (const generator of Object.values(byId ?? {})) {
      const kind = provenance.generators[generator]?.kind;
      if (kind) counts[kind] += 1;
    }
  }
  return counts;
}

/** The slim provenance a page passes to an image caption. */
export interface ImageNote {
  kind: ImageProvenanceKind;
  label: string;
}

/**
 * Caption data for an entity's illustrative image, or undefined when the
 * image is sourced artwork (credited elsewhere) or has no record. Call on
 * the server and pass the result down as a prop.
 */
export function getIllustrativeImageNote(
  entityType: ImageEntityType,
  id: string,
): ImageNote | undefined {
  const image = getImageProvenance(entityType, id);
  if (!image || !isIllustrativeImage(image)) return undefined;
  return { kind: image.kind, label: image.label };
}

/** "a deity", "an island": picks the article from the noun's first letter. */
function withArticle(noun: string): string {
  return `${/^[aeiou]/i.test(noun) ? "an" : "a"} ${noun}`;
}

/** "Greek Pantheon" reads better as "the Greek Pantheon"; a bare culture name does not. */
function withThe(tradition: string): string {
  return /^the\s/i.test(tradition) ||
    !/(pantheon|tradition|traditions|mythology)\b/i.test(tradition)
    ? tradition
    : `the ${tradition}`;
}

/** Lowercase noun for an entity type or catalog subtype ("sacred_site" -> "sacred site"). */
function nounFor(type: string | undefined, fallback: string): string {
  const noun = (type ?? "").replace(/[_-]/g, " ").trim().toLowerCase();
  // "other" and "tradition" describe the catalog row, not the thing pictured.
  return noun && noun !== "other" ? noun : fallback;
}

/**
 * Generate accessible descriptive alt text for an entity image.
 *
 * Procedural plates read "Name plate for {name}". AI illustrations are
 * phrased per entity type so each reads as a sentence fragment:
 *   deity      "Illustration of Zeus, a deity of the Greek Pantheon"
 *   hero       "Illustration of Hector, a hero of the Greek Pantheon"
 *   creature   "Illustration of Cerberus, a creature of the Greek Pantheon"
 *   location   "Illustration of Delphi, a sacred site of the Greek Pantheon"
 *   artifact   "Illustration of Mjolnir, a weapon of the Norse Pantheon"
 *   story      "Illustration of the myth "Title" from the Norse Pantheon"
 *   pantheon   "Illustration for Greek Pantheon" (its own name is the tradition)
 * The tradition is optional and its clause is left out when absent.
 */
export function generateEntityAlt({
  name,
  tradition,
  type,
  entityType,
  slug,
}: {
  name: string;
  tradition?: string;
  type?: string;
  entityType?: ImageEntityType;
  slug?: string;
}): string {
  const prov =
    entityType && slug ? getImageProvenance(entityType, slug) : undefined;
  if (prov?.kind === "illustration-procedural") {
    return `Name plate for ${name}`;
  }
  if (entityType === "pantheon") {
    return `Illustration for ${name}`;
  }
  const origin = tradition ? ` of ${withThe(tradition)}` : "";
  if (entityType === "story") {
    return tradition
      ? `Illustration of the ${nounFor(type, "myth")} "${name}" from ${withThe(tradition)}`
      : `Illustration of the ${nounFor(type, "myth")} "${name}"`;
  }
  const noun = nounFor(type, entityType?.replace(/_/g, " ") ?? "figure");
  return `Illustration of ${name}, ${withArticle(noun)}${origin}`;
}
