/**
 * Image provenance for catalog entities.
 *
 * Every entity image is an illustration made for this project (AI-generated
 * or a procedural "archival plate"), not historical artwork. The data lives
 * in `src/data/image-provenance.json`, generated by
 * `scripts/build_image_provenance.py`. UI can use `getImageProvenance` to
 * label images, e.g. "Illustrative image (AI-generated)".
 */
import provenanceData from "@/data/image-provenance.json";
import type { ImageEntityType, ImageProvenanceKind } from "@/lib/schemas";

export type { ImageEntityType, ImageProvenanceKind } from "@/lib/schemas";

export interface ImageProvenance {
  /** Key in the generators table, e.g. "ai-illustration". */
  generator: string;
  kind: ImageProvenanceKind;
  /** Short human label, e.g. "AI-generated illustration". */
  label: string;
  description: string;
  license?: string;
  source?: string;
  /** Repository scripts that produced images of this kind. */
  scripts?: string[];
}

interface ProvenanceFile {
  generators: Record<string, Omit<ImageProvenance, "generator">>;
  entities: Partial<Record<ImageEntityType, Record<string, string>>>;
}

const provenance = provenanceData as unknown as ProvenanceFile;

/**
 * Provenance of the image for `id` in the `entityType` catalog, or
 * undefined when the entity has no local image on record.
 */
export function getImageProvenance(
  entityType: ImageEntityType,
  id: string,
): ImageProvenance | undefined {
  const generator = provenance.entities[entityType]?.[id];
  if (!generator) return undefined;
  const details = provenance.generators[generator];
  if (!details) return undefined;
  return { generator, ...details };
}

/** True for images made for the project rather than sourced artwork. */
export function isIllustrativeImage(
  image: Pick<ImageProvenance, "kind"> | undefined,
): boolean {
  return (
    image?.kind === "illustration-ai" ||
    image?.kind === "illustration-procedural"
  );
}
