/**
 * Pre-computed lookup tables mapping entity slugs to pantheon IDs.
 * Kept lightweight (~9 KB) so client routing (like ambient audio and theme sync)
 * can instantly identify cultural context without loading the 586 KB deities.json
 * or 466 KB stories.json into the browser.
 */

export const DEITY_PANTHEON_MAP: Record<string, string> = {
  zeus: "greek-pantheon",
  hera: "greek-pantheon",
  poseidon: "greek-pantheon",
  hades: "greek-pantheon",
  athena: "greek-pantheon",
  apollo: "greek-pantheon",
  artemis: "greek-pantheon",
  ares: "greek-pantheon",
  aphrodite: "greek-pantheon",
  hermes: "greek-pantheon",
  dionysus: "greek-pantheon",
  demeter: "greek-pantheon",
  hephaestus: "greek-pantheon",
  hestia: "greek-pantheon",
  odin: "norse-pantheon",
  thor: "norse-pantheon",
  loki: "norse-pantheon",
  frigg: "norse-pantheon",
  freyja: "norse-pantheon",
  baldur: "norse-pantheon",
  tyr: "norse-pantheon",
  heimdall: "norse-pantheon",
  njord: "norse-pantheon",
  freyr: "norse-pantheon",
  fenrir: "norse-pantheon",
  hel: "norse-pantheon",
  sif: "norse-pantheon",
  ra: "egyptian-pantheon",
  osiris: "egyptian-pantheon",
  isis: "egyptian-pantheon",
  horus: "egyptian-pantheon",
  set: "egyptian-pantheon",
  anubis: "egyptian-pantheon",
  thoth: "egyptian-pantheon",
  bastet: "egyptian-pantheon",
  hathor: "egyptian-pantheon",
  maat: "egyptian-pantheon",
  nephthys: "egyptian-pantheon",
  sekhmet: "egyptian-pantheon",
  sobek: "egyptian-pantheon",
  jupiter: "roman-pantheon",
  juno: "roman-pantheon",
  neptune: "roman-pantheon",
  mars: "roman-pantheon",
  venus: "roman-pantheon",
  minerva: "roman-pantheon",
  "apollo-roman": "roman-pantheon",
  diana: "roman-pantheon",
  mercury: "roman-pantheon",
  bacchus: "roman-pantheon",
  vulcan: "roman-pantheon",
  ceres: "roman-pantheon",
  vesta: "roman-pantheon",
  janus: "roman-pantheon",
  brahma: "hindu-pantheon",
  vishnu: "hindu-pantheon",
  shiva: "hindu-pantheon",
  lakshmi: "hindu-pantheon",
  saraswati: "hindu-pantheon",
  parvati: "hindu-pantheon",
  durga: "hindu-pantheon",
  kali: "hindu-pantheon",
  ganesha: "hindu-pantheon",
  hanuman: "hindu-pantheon",
  rama: "hindu-pantheon",
  krishna: "hindu-pantheon",
  indra: "hindu-pantheon",
  agni: "hindu-pantheon",
  izanagi: "japanese-pantheon",
  izanami: "japanese-pantheon",
  amaterasu: "japanese-pantheon",
  tsukuyomi: "japanese-pantheon",
  susanoo: "japanese-pantheon",
  inari: "japanese-pantheon",
  hachiman: "japanese-pantheon",
  raijin: "japanese-pantheon",
  fujin: "japanese-pantheon",
  benzaiten: "japanese-pantheon",
  dagda: "celtic-pantheon",
  morrigan: "celtic-pantheon",
  lug: "celtic-pantheon",
  brigid: "celtic-pantheon",
  danu: "celtic-pantheon",
  nuada: "celtic-pantheon",
  "manannan-mac-lir": "celtic-pantheon",
  aengus: "celtic-pantheon",
  cernunnos: "celtic-pantheon",
  ogma: "celtic-pantheon",
  "dian-cecht": "celtic-pantheon",
  goibniu: "celtic-pantheon",
  aine: "celtic-pantheon",
  midir: "celtic-pantheon",
  quetzalcoatl: "aztec-pantheon",
  huitzilopochtli: "aztec-pantheon",
  tezcatlipoca: "aztec-pantheon",
  coatlicue: "aztec-pantheon",
  xochiquetzal: "aztec-pantheon",
  tlazolteotl: "aztec-pantheon",
  mayahuel: "aztec-pantheon",
  tonatiuh: "aztec-pantheon",
  xolotl: "aztec-pantheon",
  coyolxauhqui: "aztec-pantheon",
  xiuhtecuhtli: "aztec-pantheon",
  tlaltecuhtli: "aztec-pantheon",
  "jade-emperor": "chinese-pantheon",
  "sun-wukong": "chinese-pantheon",
  guanyin: "chinese-pantheon",
  nezha: "chinese-pantheon",
  "erlang-shen": "chinese-pantheon",
  "chang-e": "chinese-pantheon",
  "guan-yu": "chinese-pantheon",
  "zao-jun": "chinese-pantheon",
  "lei-gong": "chinese-pantheon",
  mazu: "chinese-pantheon",
  "xi-wangmu": "chinese-pantheon",
  pangu: "chinese-pantheon",
  "hou-yi": "chinese-pantheon",
  nuwa: "chinese-pantheon",
  anu: "mesopotamian-pantheon",
  enlil: "mesopotamian-pantheon",
  enki: "mesopotamian-pantheon",
  inanna: "mesopotamian-pantheon",
  marduk: "mesopotamian-pantheon",
  shamash: "mesopotamian-pantheon",
  "sin-nanna": "mesopotamian-pantheon",
  tiamat: "mesopotamian-pantheon",
  ereshkigal: "mesopotamian-pantheon",
  nergal: "mesopotamian-pantheon",
  gilgamesh: "mesopotamian-pantheon",
  enkidu: "mesopotamian-pantheon",
  kukulkan: "mesoamerican-pantheon",
  itzamna: "mesoamerican-pantheon",
  "ix-chel": "mesoamerican-pantheon",
  chaac: "mesoamerican-pantheon",
  "ah-puch": "mesoamerican-pantheon",
  tlaloc: "mesoamerican-pantheon",
  "xipe-totec": "mesoamerican-pantheon",
  mictlantecuhtli: "mesoamerican-pantheon",
  "hun-hunahpu": "mesoamerican-pantheon",
  "hero-twins": "mesoamerican-pantheon",
  chalchiuhtlicue: "mesoamerican-pantheon",
  maui: "polynesian-pantheon",
  pele: "polynesian-pantheon",
  tangaroa: "polynesian-pantheon",
  tane: "polynesian-pantheon",
  tu: "polynesian-pantheon",
  rongo: "polynesian-pantheon",
  hina: "polynesian-pantheon",
  "papa-polynesian": "polynesian-pantheon",
  rangi: "polynesian-pantheon",
  haumea: "polynesian-pantheon",
  namaka: "polynesian-pantheon",
  poliahu: "polynesian-pantheon",
  hiiaka: "polynesian-pantheon",
  tawhirimatea: "polynesian-pantheon",
  olodumare: "yoruba-pantheon",
  obatala: "yoruba-pantheon",
  ogun: "yoruba-pantheon",
  shango: "yoruba-pantheon",
  oshun: "yoruba-pantheon",
  yemoja: "yoruba-pantheon",
  eshu: "yoruba-pantheon",
  oya: "yoruba-pantheon",
  orunmila: "yoruba-pantheon",
  osanyin: "yoruba-pantheon",
  "nana-buruku": "yoruba-pantheon",
  shopona: "yoruba-pantheon",
  ryujin: "japanese-pantheon",
  ebisu: "japanese-pantheon",
  daikokuten: "japanese-pantheon",
  "ame-no-uzume": "japanese-pantheon",
  kagutsuchi: "japanese-pantheon",
  okuninushi: "japanese-pantheon",
  prometheus: "greek-pantheon",
  perseus: "greek-pantheon",
  persephone: "greek-pantheon",
  oduduwa: "yoruba-pantheon",
  olokun: "yoruba-pantheon",
  aje: "yoruba-pantheon",
  aganju: "yoruba-pantheon",
  ibeji: "yoruba-pantheon",
  ori: "yoruba-pantheon",
  anansi: "akan-pantheon",
  nyame: "akan-pantheon",
  "kinich-ahau": "mesoamerican-pantheon",
  "yum-kaax": "mesoamerican-pantheon",
  camazotz: "mesoamerican-pantheon",
  "ek-chuaj": "mesoamerican-pantheon",
  xochipilli: "mesoamerican-pantheon",
  centeotl: "mesoamerican-pantheon",
  perun: "slavic-pantheon",
  veles: "slavic-pantheon",
  mokosh: "slavic-pantheon",
  svarog: "slavic-pantheon",
  dazhbog: "slavic-pantheon",
  stribog: "slavic-pantheon",
  khors: "slavic-pantheon",
  simargl: "slavic-pantheon",
  svarozhich: "slavic-pantheon",
  svantevit: "slavic-pantheon",
  triglav: "slavic-pantheon",
  chernobog: "slavic-pantheon",
  "sky-woman": "haudenosaunee-pantheon",
  sapling: "haudenosaunee-pantheon",
  flint: "haudenosaunee-pantheon",
  turtle: "haudenosaunee-pantheon",
  raven: "tlingit-haida-pantheon",
  "fog-woman": "tlingit-haida-pantheon",
  "chief-fog-over-the-salmon": "tlingit-haida-pantheon",
  "naas-shaak-aankawu": "tlingit-haida-pantheon",
  "asase-yaa": "akan-pantheon",
  tano: "akan-pantheon",
  bia: "akan-pantheon",
  hinon: "haudenosaunee-pantheon",
  "earth-holder": "haudenosaunee-pantheon",
  "sky-womans-daughter": "haudenosaunee-pantheon",
  gaha: "haudenosaunee-pantheon",
  "three-sisters": "haudenosaunee-pantheon",
  "dew-eagle": "haudenosaunee-pantheon",
  petrel: "tlingit-haida-pantheon",
  "old-woman-underneath": "tlingit-haida-pantheon",
  djilaqons: "tlingit-haida-pantheon",
  "master-carpenter": "tlingit-haida-pantheon",
};

export const STORY_PANTHEON_MAP: Record<string, string> = {
  titanomachy: "greek-pantheon",
  ragnarok: "norse-pantheon",
  "creation-myth-norse": "norse-pantheon",
  "death-of-baldur": "norse-pantheon",
  "binding-of-fenrir": "norse-pantheon",
  yggdrasil: "norse-pantheon",
  "creation-heliopolis": "egyptian-pantheon",
  "osiris-myth": "egyptian-pantheon",
  "ra-journey": "egyptian-pantheon",
  contendings: "egyptian-pantheon",
  "weighing-heart": "egyptian-pantheon",
  aeneid: "roman-pantheon",
  "romulus-remus": "roman-pantheon",
  "sabine-women": "roman-pantheon",
  "cupid-psyche": "roman-pantheon",
  ramayana: "hindu-pantheon",
  mahabharata: "hindu-pantheon",
  "churning-ocean": "hindu-pantheon",
  "creation-japan": "japanese-pantheon",
  "amaterasu-cave": "japanese-pantheon",
  "yamata-no-orochi": "japanese-pantheon",
  "cath-maige-tuired": "celtic-pantheon",
  "children-lir": "celtic-pantheon",
  "five-suns": "aztec-pantheon",
  "journey-to-west": "chinese-pantheon",
  "archer-yi": "chinese-pantheon",
  "chang-e-moon": "chinese-pantheon",
  "pangu-creation": "chinese-pantheon",
  "nezha-legend": "chinese-pantheon",
  "cowherd-weaver": "chinese-pantheon",
  "nuwa-repairs-sky": "chinese-pantheon",
  "prometheus-fire": "greek-pantheon",
  "perseus-medusa": "greek-pantheon",
  "theseus-minotaur": "greek-pantheon",
  "orpheus-eurydice": "greek-pantheon",
  "trojan-war": "greek-pantheon",
  "mead-of-poetry": "norse-pantheon",
  "thors-journey-utgard": "norse-pantheon",
  "odins-sacrifice": "norse-pantheon",
  "book-of-dead-journey": "egyptian-pantheon",
  "sekhmet-rampage": "egyptian-pantheon",
  "krishna-childhood": "hindu-pantheon",
  "ganesha-creation": "hindu-pantheon",
  "izanagi-yomi": "japanese-pantheon",
  "tale-of-hoori": "japanese-pantheon",
  "cattle-raid-cooley": "celtic-pantheon",
  "wooing-of-etain": "celtic-pantheon",
  "dream-of-aengus": "celtic-pantheon",
  "sons-of-tuireann": "celtic-pantheon",
  "death-of-cu-chulainn": "celtic-pantheon",
  "voyage-of-bran": "celtic-pantheon",
  "epic-of-gilgamesh": "mesopotamian-pantheon",
  "inanna-descent": "mesopotamian-pantheon",
  "enuma-elish": "mesopotamian-pantheon",
  "flood-utnapishtim": "mesopotamian-pantheon",
  "gilgamesh-enkidu-friendship": "mesopotamian-pantheon",
  "quetzalcoatl-mictlan": "mesoamerican-pantheon",
  "hero-twins-popol-vuh": "mesoamerican-pantheon",
  "maize-god-rebirth": "mesoamerican-pantheon",
  "maui-fishes-up-islands": "polynesian-pantheon",
  "maui-slows-the-sun": "polynesian-pantheon",
  "maui-steals-fire": "polynesian-pantheon",
  "pele-and-hiiaka": "polynesian-pantheon",
  "separation-of-rangi-and-papa": "polynesian-pantheon",
  "yoruba-creation": "yoruba-pantheon",
  "shango-becomes-orisha": "yoruba-pantheon",
  "oshun-saves-world": "yoruba-pantheon",
  "eshu-two-friends": "yoruba-pantheon",
  "ogun-shango-contest": "yoruba-pantheon",
  "birth-of-huitzilopochtli": "aztec-pantheon",
  "quetzalcoatl-fall-exile": "aztec-pantheon",
  "journey-to-mictlan": "aztec-pantheon",
  "anansi-bought-stories": "akan-pantheon",
  "oduduwa-creation-earth": "yoruba-pantheon",
  "first-twins-ibeji": "yoruba-pantheon",
  "house-of-bats": "mesoamerican-pantheon",
  "rape-of-proserpina": "roman-pantheon",
  "lucretia-fall-kings": "roman-pantheon",
  "labors-of-hercules": "roman-pantheon",
  "dido-aeneas": "roman-pantheon",
  "aztec-creation-humanity": "aztec-pantheon",
  "flaying-xipe-totec": "aztec-pantheon",
  "xochiquetzal-forbidden": "aztec-pantheon",
  "four-hundred-rabbits": "aztec-pantheon",
  "narasimha-prahlada": "hindu-pantheon",
  "shakuntala-dushyanta": "hindu-pantheon",
  "shiva-parvati-marriage": "hindu-pantheon",
  "hanuman-leap-lanka": "hindu-pantheon",
  "icarus-daedalus": "greek-pantheon",
  "judgment-of-paris": "greek-pantheon",
  "pygmalion-galatea": "greek-pantheon",
  "echo-narcissus": "greek-pantheon",
  "susanoo-banishment": "japanese-pantheon",
  "okuninushi-trials": "japanese-pantheon",
  "atrahasis-flood": "mesopotamian-pantheon",
  "etana-and-the-eagle": "mesopotamian-pantheon",
  "maui-and-hina-death": "polynesian-pantheon",
  "hina-maui-lengthened-day": "polynesian-pantheon",
  "vladimirs-pantheon-980": "slavic-pantheon",
  "perun-and-veles": "slavic-pantheon",
  "svantevits-oracle-horse": "slavic-pantheon",
  "vasilisa-the-beautiful": "slavic-pantheon",
  "sky-woman-and-turtle-island": "haudenosaunee-pantheon",
  "the-twins-sapling-and-flint": "haudenosaunee-pantheon",
  "peacemaker-great-law-of-peace": "haudenosaunee-pantheon",
  "raven-steals-the-light": "tlingit-haida-pantheon",
  "raven-and-the-first-men": "tlingit-haida-pantheon",
  "tano-and-bia-divide-the-land": "akan-pantheon",
  "hinon-and-the-horned-serpent": "haudenosaunee-pantheon",
  "hiawatha-and-the-condolence": "haudenosaunee-pantheon",
  "origin-of-the-three-sisters": "haudenosaunee-pantheon",
  "raven-and-petrel": "tlingit-haida-pantheon",
  "kats-and-the-bear-wife": "tlingit-haida-pantheon",
  "natsilane-and-the-killer-whales": "tlingit-haida-pantheon",
};

/**
 * Resolve the pantheonId for any route in Mythos.
 * Supports:
 * - /pantheons/[slug] (e.g. /pantheons/greek -> greek-pantheon)
 * - /deities/[slug]   (e.g. /deities/zeus -> greek-pantheon)
 * - /stories/[slug]   (e.g. /stories/ragnarok -> norse-pantheon)
 * Returns null for general routes (e.g. /about, /timeline).
 */
export function resolveRoutePantheonId(pathname: string | null): string | null {
  if (!pathname) return null;

  // 1. Direct pantheon hub route: /pantheons/[slug]
  const pantheonMatch = pathname.match(/^\/pantheons\/([a-z0-9-]+)/);
  if (pantheonMatch) {
    const slug = pantheonMatch[1];
    return slug.endsWith("-pantheon") ? slug : `${slug}-pantheon`;
  }

  // 2. Deity detail route: /deities/[slug]
  const deityMatch = pathname.match(/^\/deities\/([a-z0-9-]+)/);
  if (deityMatch) {
    const slug = deityMatch[1];
    return DEITY_PANTHEON_MAP[slug] || null;
  }

  // 3. Story detail route: /stories/[slug]
  const storyMatch = pathname.match(/^\/stories\/([a-z0-9-]+)/);
  if (storyMatch) {
    const slug = storyMatch[1];
    return STORY_PANTHEON_MAP[slug] || null;
  }

  return null;
}
